theme: jekyll-theme-minimal
title: 'Adv Topics in scRNA-Seq: Trajectory and Velocity Analysis'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome

  - heading: Support
  - title: Using Slack in this workshop
    url: base/slack
  - title: Using Zoom in this workshop
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: CLI
    url: base/cli_prerequisites
  - title: R
    url: base/r_prerequisites
  - title: More Materials: Intro CLI
    url: https://ucdavis-bioinformatics-training.github.io/2021-June-Introduction-to-the-Command-Line-for-Bioinformatics/
  - title: More Materials: Intro R
    url: https://ucdavis-bioinformatics-training.github.io/2021-June-Introduction-to-R-for-Bioinformatics/

  - heading: Monocle Trajectory Analysis
  - title: Monocle
    url: data_analysis/adv_scrnaseq_monocle

  # - title: Generating Expression Matrices
  #   url: data_reduction/Expression_Matrix
  # - title: Expression project setup
  #   url: data_reduction/project_setup_counting

  - heading: Velocity Analysis
  - title: scRNA analysis prepare, part 2
    url: data_analysis/scrna_analysis_prepare2_fixed
  - title: Velocity analysis
    url:   data_reduction/Velocyto
  - title: Velocity  analysis
    url:  data_analysis/Velocyto_fixed

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-August-Advanced-Topics-in-Single-Cell-RNA-Seq-Trajectory-and-Velocity
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
